name: Messedaglia
description: Applicazione (quasi) ufficiale del liceo "A. Messedaglia"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  account_selector: ^1.0.1
  app_settings: ^4.0.4
  auto_size_text: ^2.1.0
  autocomplete_textfield: ^1.7.3
  circular_splash_transition: ^0.2.1
  connectivity: ^0.4.8+1
  convert: ^2.1.1
  cupertino_icons: ^0.1.2
  device_info: ^0.4.1+4
  easy_permission_validator: ^2.0.0
  ext_storage: ^1.0.2
  firebase: ^7.3.2
  firebase_crashlytics: ^0.2.3
  fl_chart: ^0.8.0
  flare_flutter: ^2.0.6
  floating_search_bar: ^0.3.0
  flutter_calendar_carousel: ^1.4.10
  flutter_dash: ^0.0.1
  flutter_holo_date_picker: ^0.1.3+2
  flutter_local_notifications: ^1.2.0+4
  flutter_phoenix: ^0.1.0
  flutter_svg: ^0.19.1
  http: ^0.12.0+4
  image_downloader: ^0.20.1
  image_picker: ^0.6.6+1
  intl: ^0.16.1
  liquid_pull_to_refresh: ^1.1.1
  marquee: ^1.3.1
  material_design_icons_flutter: ^4.0.0
  modal_progress_hud: ^0.1.3
  open_file: ^3.0.3
  overlay_support: ^1.0.5
  package_info: ^0.4.3+2
  path: ^1.6.4
  path_parsing: ^0.1.4
  path_provider: ^1.5.1
  platform_alert_dialog: ^1.0.0+2
  positioned_tap_detector: ^1.0.3
  preferences: ^5.1.0
  rounded_loading_button: ^1.0.4
  simple_mapper: ^1.1.0
  sliding_sheet: ^0.4.1
  sqflite: ^1.3.0
  url_launcher: ^5.4.2
  video_player: ^0.10.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1

flutter_launcher_name:
  name: "Messe App"

# flutter_icons:
#   ios: true
#   android: true
#   image_path_ios: "images/Icon IOS dark.png"
#   image_path_android: "images/Icon ANDROID.png"
#   adaptive_icon_background: "images/Icon Background.png"
#   adaptive_icon_foreground: "images/Icon Foreground.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - flare/
    - videos/
    - icons/
    #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CoreSans
      fonts:
        - asset: fonts/CoreSansG-Regular.ttf

    - family: CoreSansRounded
      fonts:
        - asset: fonts/CoreSansGRounded-Medium.ttf

    - family: TeeFranklin
      fonts:
        - asset: fonts/TeeFranklin-Medium.otf

    - family: MenuGrid
      fonts:
        - asset: fonts/MenuGrid.ttf

    - family: CalendarMonth
      fonts:
        - asset: fonts/CalendarMonth.ttf
    # - family: Ewert
    #   fonts:
    #     - asset: fonts/Ewert-Regular.ttf
  #     - asset: fonts/Tee_franklin_bold.ttf
  #        style: rounded
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
